name: JS-test-two

on:
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build Angular Project and Run PSE

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          app_token: ${{secrets.IR_TOKEN}}
      # ============= InvisiRisk Setup End =============
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
